<a href="https://colab.research.google.com/github/asmaaahmedm/lab/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [3]:
import numpy as np

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [4]:
list = [1,2,3,4]
arr = np.array(list)
arr

array([1, 2, 3, 4])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [6]:
null_vector = np.zeros(9)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [10]:
arr = np.zeros((3, 4))
memory_size = arr.size * arr.itemsize
print(memory_size)


96


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [12]:
arr = np.zeros(12)
arr[5] = 1
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [16]:
np.arange(20,60)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [18]:
reversed_arr = arr[::-1]
print("Reversed:", reversed_arr)

Reversed: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [19]:
arr = np.arange(12, 21).reshape(3, 3)
print(arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [20]:
arr = np.array([3, 7, 0, 0, 9, 0])

indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [21]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [22]:
arr = np.random.random((2, 2, 2))
print(arr)

[[[0.76890414 0.19651111]
  [0.83004823 0.89800901]]

 [[0.28497072 0.23816849]
  [0.94387649 0.64028223]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [23]:
array = np.random.rand(9, 9)

min_val = array.min()
max_val = array.max()

print(array)
print(min_val)
print(max_val)

[[0.44422382 0.70447716 0.19006763 0.74144865 0.0564335  0.00903968
  0.27953812 0.58273263 0.80686204]
 [0.39279495 0.67504143 0.35179024 0.22934659 0.27125476 0.35118609
  0.04795815 0.99278787 0.95464727]
 [0.10917036 0.58270624 0.33317934 0.48510548 0.42454434 0.65681947
  0.56534942 0.56789146 0.78056043]
 [0.07369011 0.11995478 0.14807651 0.46179089 0.46404951 0.87014834
  0.46570932 0.22199755 0.35742376]
 [0.06915068 0.91813556 0.77118059 0.68665728 0.65979413 0.35790596
  0.17245141 0.16323273 0.39317514]
 [0.10758435 0.6761976  0.7849313  0.97811177 0.93173138 0.41770806
  0.68873382 0.2665446  0.4601261 ]
 [0.41330012 0.24111181 0.33985197 0.99493575 0.73371122 0.58364626
  0.93804738 0.83150917 0.84741756]
 [0.7338326  0.79907738 0.71491704 0.75658074 0.69912436 0.09538042
  0.98704818 0.39569953 0.89126882]
 [0.90192766 0.50346209 0.79055383 0.90029236 0.9214345  0.96504469
  0.05494445 0.77496947 0.05845365]]
0.009039676353841952
0.994935751358335


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [24]:
vector = np.random.rand(20)
mean_val = vector.mean()

print(vector)
print(mean_val)

[0.62646341 0.67879499 0.19724655 0.04379921 0.25197893 0.285355
 0.66099335 0.36192699 0.96703497 0.30561509 0.70975023 0.85179883
 0.88741333 0.25610906 0.01272219 0.50870006 0.07647259 0.63776166
 0.63223821 0.24232254]
0.4597248591678378


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [25]:
array = np.ones((5, 5), dtype=int)
array[1:-1, 1:-1] = 0

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [26]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array)
print(array_with_border)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


# #### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [27]:
matrix = np.zeros((6, 6), dtype=int)
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 1 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [28]:
matrix = np.zeros((6, 6), dtype=int)

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [29]:
shape = (8, 9, 10)
index = np.unravel_index(99, shape)

print( index)


(np.int64(1), np.int64(0), np.int64(9))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [30]:
checkerboard_2x2 = np.array([[1, 0], [0, 1]])
checkerboard_8x8 = np.tile(checkerboard_2x2, (4, 4))

print(checkerboard_8x8)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [31]:
matrix = np.random.rand(6, 6)
mean = matrix.mean()
std = matrix.std()
normalized_matrix = (matrix - mean) / std

print(matrix)
print(normalized_matrix)


[[0.56942663 0.00324226 0.52433942 0.91153033 0.81150162 0.67736844]
 [0.22404866 0.80884301 0.54080713 0.93885596 0.2901507  0.74117597]
 [0.02706546 0.86295646 0.26573557 0.30653745 0.90877008 0.32518735]
 [0.17498698 0.06616873 0.51978907 0.81561386 0.50627547 0.21035645]
 [0.76452395 0.8418229  0.47517838 0.36507377 0.92507855 0.26203732]
 [0.71479069 0.49784067 0.29243212 0.04234752 0.20345618 0.68581776]]
[[ 0.23057819 -1.72911694  0.07452093  1.41467825  1.06845575  0.60418975]
 [-0.9648549   1.05925367  0.13151948  1.50925856 -0.73606043  0.82504239]
 [-1.6466593   1.24655283 -0.82056686 -0.67934211  1.40512436 -0.61479048]
 [-1.13466872 -1.51131385  0.0587711   1.08268915  0.0119974  -1.0122468 ]
 [ 0.90585514  1.17340469 -0.09563681 -0.47673435  1.46157177 -0.83336734]
 [ 0.73371682 -0.01719741 -0.7281639  -1.59376458 -1.03613024  0.6334348 ]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [32]:
import numpy as np

# Create a sample array (for example, a 4x5 array of random numbers)
array = np.random.rand(4, 5)

# Number of elements
num_elements = array.size

# Length of one element in bytes
element_size = array.itemsize

# Total bytes consumed
total_bytes = array.nbytes

print(num_elements)
print(element_size)
print(total_bytes)


20
8
160


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [33]:
matrix_a = np.random.rand(6, 3)
matrix_b = np.random.rand(3, 4)
result = np.dot(matrix_a, matrix_b)

print(matrix_a)
print(matrix_b)
print(result)


[[0.17566596 0.15472276 0.04557952]
 [0.68788807 0.65777642 0.5872948 ]
 [0.45789533 0.18515376 0.64137582]
 [0.78271106 0.47396282 0.83020162]
 [0.25141638 0.60540454 0.22033373]
 [0.86946482 0.15970141 0.97123016]]
[[0.62898553 0.47618616 0.71401942 0.27663981]
 [0.22707909 0.19305566 0.26876084 0.36672605]
 [0.43641871 0.06888099 0.98492198 0.94301244]]
[[0.1655174  0.11665936 0.21190459 0.14831912]
 [0.83834535 0.49500369 1.24638954 0.98534728]
 [0.6099625  0.297967   1.00841339 0.79939817]
 [0.96225649 0.52140249 1.50393736 1.17323401]
 [0.39176974 0.25177457 0.55923674 0.49934684]
 [1.00700865 0.51175767 1.62032218 1.21497737]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [34]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array[(array >= 3) & (array <= 8)] *= -1

print(array)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a > b : [False False]
a >= b: [False False]
a < b : [ True  True]
a <= b: [ True  True]

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [36]:
arr = np.array([1.2,2.7, -2.7, 0.0])

rounded = np.ceil(np.abs(arr)) * np.sign(arr)
print(rounded)

[ 2.  3. -3.  0.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [35]:
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([4, 5, 6, 7, 8, 9])

common_values = np.intersect1d(array1, array2)

print(common_values)


[4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`